from flask_sqlalchemy import SQLAlchemy
import sqlalchemy

db = SQLAlchemy()

class capita_poblaciones(db.Model):
    id = db.Column(db.Integer(), primary_key= True)
    fecha_capita = db.Column(db.Date)
    nombre_ips = db.Column(db.String(20))
    poblacion_total = db.Column(db.Integer())
    poblacion_total_f = db.Column(db.Integer())
    poblacion_total_m = db.Column(db.Integer())
    menores_1_ano_f = db.Column(db.Integer())
    menores_1_ano_m = db.Column(db.Integer())
    entre_1_y_4_anos_f = db.Column(db.Integer())
    entre_1_y_4_anos_m = db.Column(db.Integer())
    menores_a_5_anos_f = db.Column(db.Integer())
    menores_a_5_anos_m = db.Column(db.Integer())
    entre_5_y_14_anos_f = db.Column(db.Integer())
    entre_5_y_14_anos_anos_m = db.Column(db.Integer())
    entre_6_y_19_anos_f = db.Column(db.Integer())
    entre_6_y_19_anos_anos_m = db.Column(db.Integer())
    entre_15_y_44_anos_f = db.Column(db.Integer())
    entre_15_y_44_anos_m = db.Column(db.Integer())
    entre_45_y_59_anos_f = db.Column(db.Integer())
    entre_45_y_59_anos_m = db.Column(db.Integer())
    mayor_de_59_anos_f = db.Column(db.Integer())
    mayor_de_59_anos_m = db.Column(db.Integer())
    menores_a_1_ano = db.Column(db.Integer())
    entre_1_y_4_anos = db.Column(db.Integer())
    menores_a_5_anos = db.Column(db.Integer())
    entre_5_y_14_anos = db.Column(db.Integer())
    entre_6_y_19_anos = db.Column(db.Integer())
    entre_15_y_44_anos = db.Column(db.Integer())
    entre_45_y_59_anos = db.Column(db.Integer())
    mayores_de_59_anos = db.Column(db.Integer())
    entre_12_y_17_anos = db.Column(db.Integer())
    entre_18_y_28_anos = db.Column(db.Integer())
    entre_29_y_59_anos = db.Column(db.Integer())
    mujeres_entre_15_y_19_anos = db.Column(db.Integer())
    menores_a_16_anos = db.Column(db.Integer())
    mujeres_entre_15_y_49_anos = db.Column(db.Integer())
    mujeres_entre_10_y_49_anos = db.Column(db.Integer())
    mujeres_entre_10_y_14_anos = db.Column(db.Integer())
    mujeres_entre_14_y_49_anos = db.Column(db.Integer())
    mayores_de_18_anos = db.Column(db.Integer())
    entre_6_y_10_anos = db.Column(db.Integer())
    entre_18_y_85_anos = db.Column(db.Integer())
    mayores_de_40_anos = db.Column(db.Integer())
    menores_a_18_anos = db.Column(db.Integer())
    mujeres_mayores_igual_18_anos = db.Column(db.Integer())
    menores_a_41_anos = db.Column(db.Integer())
    menores_a_3_anos = db.Column(db.Integer())
    mayores_de_64_anos = db.Column(db.Integer())